### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by muvans** [DerrickJames/africas-talking#1]
This command does not work: composer require derrickjames/africas-talking
Is the package already available?

**Comment by DerrickJames** [comment]
@muvans There are a few things that need to be done before it becomes stable, some things came up and I couldn't complete implementation though I install it by defining the repository in my composer.json file. Pull requests are highly welcomed.

**Comment by muvans** [comment]
@DerrickJames No problem. Thanks for the update. How would you advice that I make use of this as it is now? This looks quite well documented and well thought out than any other on github, only if it would be complete. Let me also know how I can help contribute. Thanks.

**Comment by DerrickJames** [comment]
@muvans Thanks for showing interest. I could share a sample of my composer.json file configuration to assist you to get it up and running in your project then you could play around with it. Would that be of help to you? But you first you need to fork the project so that you're able to send pull requests. The tasks pending are tests and some few configuration for it to be composer installable.

**Comment by muvans** [comment]
Thant would be perfect. I would be happy to test and contribute too. Thank
you.

_Regards,_
_Evans Ndegwa,_
_Founder & CEO,_

_Phone_:    +254-723-220235
               +254-733-949310
_Skype_:    muvatech
_Website_: http://www.muva.co.ke

**Comment by DerrickJames** [comment]
@muvans Find the composer configuration on this gist [composer.json](https://gist.github.com/DerrickJames/f579e0b28eb0690fafd06f654724e83c)

Some of the configuration is omitted for brevity. Note, that the most important thing is to fork the repo, then clone it to your local machine. Then on a separate laravel project add the repositories property and also require the package as specified in the gist file in your composer config. Then run composer install/update.
[](url)
Let me know how it goes. Happy hacking man.
