### ISSUE TITLE
Clarification on driver implementation

### ISSUE THREAD

**Issue by gkarugi** [DerrickJames/africas-talking#2]
Great work you have btw.

I needed clarification how you have implemented the drivers to be used. 
I can see the AfricasTalking façade returns Factory, and Factory is bound to AfricasTalkingManager. 

Now to my question, is the parameter passed to the driver eg. 'sms' translated to a class e.g. the SMS driver class? 

```
$response = africasTalking()
        ->driver('sms')
        ->to(['+254721234567'])
        ->message('Test Africas Talking API service SMS driver.')
        ->send();
```

**Comment by DerrickJames** [comment]
@gkarugi thank you for your compliment.

If you look at the AfricasTalkingManager, you'll notice the `buildProvider` method which simply creates the driver instances. In the AfricasTalkingServiceProvider, we're binding our manager to the service container. Now, as long as the AfricasTalkingServiceProvider is registered in the providers array in `config/app.php` configuration file, Laravel should be able to resolve the provider when Laravel is booting up.

I'd recommend you read the "Architecture Concepts"  in Laravel docs.

Thanks and sorry for the late response.
